# Generated by Django 4.1.7 on 2023-03-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='imageURL',
        ),
    ]
