# Generated by Django 4.1.7 on 2023-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='abcd',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
