# Generated by Django 4.1.7 on 2023-03-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_abcd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='abcd',
            new_name='imageurl',
        ),
    ]
