# Generated by Django 4.1.7 on 2023-03-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_abcd_listing_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageurl',
            field=models.CharField(blank=True, default='this is default', max_length=1000, null=True),
        ),
    ]
