# Generated by Django 4.1.7 on 2023-03-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_time_alter_listing_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='time',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
